Repository AIVLE-School-3-1/algorithm-study, pull requests merged in 2023-03, with the labels that each got.

#29 Create code : 박진우 그리디
  ParkRang/BOJ 골드4 2831 댄스 파티.py
  ParkRang/Greedy/BOJ 골드5 11509 풍선 맞추기.py
  ParkRang/Greedy/BOJ 실버4 1026 보물.py
  ParkRang/Greedy/BOJ 실버4 1246 온라인 판매.py
Labels: python, easy, 박진우

#31 Create code : 안승주 해시
  beginner0107/해시/댄스파티.py
  beginner0107/해시/성격유형검사하기.py
  beginner0107/해시/전화번호 목록.py
Labels: python, easy, 안승주

#32 Merge : 윤용완 DFS/BFS
  ayocado/BFS,DFS/PGS level3 43162 네트워크.py
  ayocado/그리디/BOJ 골드4 2831 댄스파티.py
Labels: python, normal, 윤용완

#36 김형준 스택&큐
  brojoon1/그리디/BOJ 골드4 2831 댄스파티.py
  brojoon1/스택&큐/PGS level1 같은숫자는싫어.py
  brojoon1/스택&큐/PGS level2 프린터.py
  brojoon1/스택&큐/스택&큐.md
Labels: python, normal, 김형준

#37 Merge : 위예진 스택, 이진탐색
  bokkuembab/binary search/BOJ 실버2 2805 나무자르기.py
  bokkuembab/stack/BOJ 실버2 1874 스택 수열.py
Labels: python, 위예진, hard

#38 김유 트리, 그리디
  kimyoo04/그리디/BOJ 골드4 2831 댄스 파티.py
  kimyoo04/트리/BOJ 골드3 11437 LCA.py
  kimyoo04/트리/BOJ 실버4 13116 30번.py
  kimyoo04/트리/최소공통조상 LCA.md
Labels: 김유, python, easy, normal

#43 Merge : 윤용완 BFS
  ayocado/BFS,DFS/BOJ 골드4 12851 숨바꼭질2.py
  ayocado/BFS,DFS/BOJ 골드5 13549 숨바꼭질3.py
  ayocado/BFS,DFS/BOJ 실버1 1697 숨바꼭질.py
Labels: python, normal, 윤용완

#44 김유 그래프, 다익스트라, 플로이드-워셜, 우선순위큐
  kimyoo04/그래프/BOJ 실버1 1697 숨바꼭질.py
  kimyoo04/그리디/BOJ 골드4 1715 카드 정렬하기.py
  kimyoo04/다익스트라/BOJ 골드4 1753 최단경로.py
  kimyoo04/플로이드-워셜/BOJ 골드4 11404 플로이드.py
  kimyoo04/플로이드-워셜/BOJ 실버1 11403 경로 찾기.py
Labels: 김유, python, normal

#45 Create code : 박진우 이진 탐색
  ParkRang/BOJ 골드5 13549 숨바꼭질 3.py
  ParkRang/Binary_search/BOJ 골드4 2110 공유기 설치.py
  ParkRang/Binary_search/BOJ 실버2 16401 과자 나눠주기.py
  ParkRang/Binary_search/BOJ 실버4 1920 수 찾기.py
Labels: python, normal, hard, 박진우

#47 Merge : 안승주 BFS, 집합
  beginner0107/BFS/숨바꼭질3.py
  beginner0107/집합/방문길이.py
  beginner0107/집합/프렌즈4블록.py
Labels: python, hard, 안승주

#42 Jian1114
  jian1114/bfs/이지안 BOJ 골드5 13549 숨바꼭질 3.py
  jian1114/bfs/이지안 BOJ 실버1 1697 숨바꼭질.py
Labels: python, normal, 이지안

#48 Merge : 위예진 BFS
  bokkuembab/BFS/BOJ 실버1 1697 숨바꼭질.py
  bokkuembab/BFS/BOJ 실버1 2178 미로 탐색.py
  bokkuembab/BFS/BOJ 실버2 1260 DFS와 BFS.py
Labels: python, 위예진, hard

#49 김형준 bfs
  brojoon1/bfs/BOJ 골드5 13549 숨바꼭질3.py
  brojoon1/bfs/PGS level2 게임 맵 최단거리.py
  brojoon1/bfs/PGS level2 타겟넘버.py
Labels: python, normal, 김형준

#51 박희원 bfs
  heewon00/bfs/BOJ 골드5 13549 숨바꼭질 3.py
Labels: normal, 박희원

#52 Merge : 김인재 BFS
  Pang-dachu/DFS and BFS/김인재 BOJ 골드5 7569 토마토.py
  Pang-dachu/DFS and BFS/김인재 BOJ 골드5 7576 토마토.py
  Pang-dachu/Graph/BOJ 골5 숨바꼭질3.py
  Pang-dachu/Graph/BOJ 실1 숨바꼭질.py
Labels: normal, 김인재

#53 Merge : 안승주 bfs, greedy, sort
  beginner0107/정렬/게임맵최단거리.java
  beginner0107/정렬/게임맵최단거리.py
  beginner0107/정렬/경로찾기.java
  beginner0107/정렬/덧칠하기.java
  beginner0107/정렬/덧칠하기.py
  beginner0107/정렬/파일명정렬.java
  beginner0107/정렬/파일명정렬.py
Labels: python, normal, 안승주

#54 김유 구현, 그래프
  kimyoo04/구현/PGS level3 42627 디스크 컨트롤러.py
  kimyoo04/그래프/BOJ 골드4 12851 숨바꼭질 2.py
  kimyoo04/그래프/BOJ 골드4 13549 숨바꼭질 3.py
  kimyoo04/그래프/BOJ 골드5 7569 토마토.py
  kimyoo04/그래프/BOJ 골드5 7576 토마토.py
Labels: 김유, python, easy, normal

#56 Merge : 위예진 BFS
  bokkuembab/BFS/BOJ 골드 5 7569 토마토.py
  bokkuembab/BFS/BOJ 골드5 7576 토마토.py
  bokkuembab/simulation/BOJ 골드5 14503 로봇 청소기.py
Labels: python, 위예진, normal

#58 Merge : 박희원 트리
  heewon00/bfs/BOJ 골드5 7569 토마토.py
  heewon00/스택, 큐/PGS level2 다리를 지나는 트럭.py
  heewon00/스택, 큐/PGS level2 올바른 괄호.py
  heewon00/스택, 큐/PGS level2 프린터.py
Labels: normal

#60 Merge : 윤용완 BFS
  ayocado/BFS,DFS/BOJ 골드5 7569 토마토.py
Labels: python, normal, 윤용완

#61 Create code 박진우 : TwoPointer
  ParkRang/BOJ 골드5 7569 토마토.py
  ParkRang/Two_pointer/BOJ 골드5 2230 수 고르기.py
  ParkRang/Two_pointer/BOJ 실버3 2559 수열.py
  ParkRang/Two_pointer/BOJ 실버4 1940 주몽.py
Labels: normal

#63 Create code : 이지안 BOJ 골드5 7569 토마토
  jian1114/bfs/이지안 BOJ 골드5 7576 토마토.py
Labels: python, normal, 이지안

#65 Pang dachu
  Pang-dachu/Stack and Queue/김인재 PGS level2 기능개발.py
  Pang-dachu/Stack and Queue/김인재 PGS level2 프린터.py
  Pang-dachu/test.txt
Labels: easy, 김인재

#66 Merge : 김형준 투 포인터
  brojoon1/구현/BOJ 실버3 11659 구간 합 구하기4.py
  brojoon1/투 포인터/BOJ 골드4 1806 부분합.py
Labels: python, normal, 김형준

#67 Merge : 안승주 DP, 분할 정복 알고리즘, 정렬
  beginner0107/DP/N타일링.java
  beginner0107/DP/N타일링.py
  beginner0107/수열/부분합.java
  beginner0107/수열/부분합.py
  beginner0107/재귀/쿼드압축.java
  beginner0107/재귀/쿼드압축후개수세기.py
  beginner0107/정렬/가장큰수.java
  beginner0107/정렬/가장큰수.py
Labels: python, normal, 안승주

#68 Merge : 위예진 Dijkstra
  bokkuembab/Dijkstra/BOJ 골드5 1916 최소비용 구하기.py
  bokkuembab/Dijkstra/BOJ 골드5 5972 택배 배송.py
  bokkuembab/Dijkstra/BOJ 실버1 1446 지름길.py
  bokkuembab/prefix sum/BOJ 실버1 11660 구간 합 구하기 5.py
  bokkuembab/prefix sum/BOJ 실버3 11659 구간 합 구하기 4.py
Labels: python, 위예진, hard

#69 김유 그리디, 투 포인터
  kimyoo04/그리디/BOJ 실버1 1931 회의실 배정.py
  kimyoo04/투 포인터/BOJ 골드4 1806 부분합.py
  kimyoo04/투 포인터/BOJ 실버2 11659 구간 합 구하기 4.py
Labels: 김유, python, easy

#72 Merge : 윤용완 투 포인터
  ayocado/투 포인터/BOJ 실버3 11659 구간 합 구하기4.py
Labels: python, normal, 윤용완

#74 Create code : 박진우 BruteForce
  ParkRang/BOJ 실버3 11659 구간 합 구하기 4.py
  ParkRang/BruteForce/BOJ 1057 실버4 토너먼트.py
  ParkRang/BruteForce/BOJ 1436 실버5 영화감독 숌.py
  ParkRang/BruteForce/BOJ 5555 실버5 반지.py
  ParkRang/BruteForce/BOJ 실버4 1969 DNA.py
Labels: easy

#75 Heewon00
  heewon00/구현/BOJ 실버3 11659 구간 합 구하기4.py
  heewon00/그리디/PGS level2 42860 조이스틱.py
  heewon00/그리디/PGS level2 42885 구명보트.py
  heewon00/그리디/PGS level3 42861 섬 연결하기.py
  heewon00/투포인터/BOJ 골드4 1806 부분합.py
Labels: normal
