Repository AIVLE-School-3-1/algorithm-study, pull requests merged in 2023-02, with the labels that each got.

#2 Merge : 김인재 DFS and BFS
  Pang-dachu/DFS and BFS/DFS and BFS.md
  Pang-dachu/DFS and BFS/PGS level2 게임 맵 최단거리.py
  Pang-dachu/DFS and BFS/PGS level2 타겟 넘버.py
  Pang-dachu/DFS and BFS/PGS level3 여행경로.py
Labels: python, normal, 김인재

#3 안승주: BFS
  beginner0107/BFS/나이트의이동.py
  beginner0107/BFS/숨바꼭질.py
  beginner0107/BFS/토마토1.py
  beginner0107/BFS/토마토2.py
Labels: normal

#6 Merge : 위예진 greedy
  bokkuembab/greedy/BOJ 실버1 1931 회의실 배정.py
  bokkuembab/greedy/PGS level1 42862 체육복.py
  bokkuembab/greedy/PGS level2 72412 순위 검색.py
Labels: python, 위예진, normal

#5 윤용완 : 해시
  ayocado/해시/PGS level1 1845 폰켓몬.ipynb
  ayocado/해시/PGS level1 42576 완주하지 못한 선수.ipynb
  ayocado/해시/PGS level2 42577 전화번호 목록.ipynb
  ayocado/해시/해시.md
Labels: python, easy, 윤용완

#7 Merge : 김유 백트래킹
  kimyoo04/백트래킹/BOJ 실버2 1182 부분수열의 합.py
  kimyoo04/백트래킹/BOJ 실버3 15649 N과 M (1).py
  kimyoo04/백트래킹/BOJ 실버3 15650 N과 M (2).py
  kimyoo04/백트래킹/백트래킹.md
Labels: 김유, python, normal

#8 Merge : 윤용완 스택,큐
  ayocado/스택,큐/PGS level1 12906 같은 숫자는 싫어.py
  ayocado/스택,큐/PGS level2 12909 올바른 괄호.py
  ayocado/스택,큐/PGS level2 42586 기능개발.py
  ayocado/스택,큐/PGS level2 42587 프린터.py
Labels: python, normal, 윤용완

#9 원세린 정렬
  1ser1n1/sort/PGS level1 42748 K번째수.py
Labels: python, easy, 원세린

#10 jian week 1 stack
  jian1114/stack/이지안 BOJ 실버2 1874 스택수열.py
  jian1114/stack/이지안 BOJ 실버4 10773 제로.py
  jian1114/stack/이지안 BOJ 실버4 10828 스택.py
  jian1114/stack/이지안 BOJ 실버4 9012 괄호.py
Labels: python, normal, 이지안

#11 박진우 20230219 스택 문제
  ParkRang/Stack/BOJ 브론즈2 17608 막대기.py
  ParkRang/Stack/PGS level2 12909 올바른괄호.py
  ParkRang/Stack/PGS level2 154539 위에 있는 큰 수 찾기.py
Labels: python, easy, normal, 박진우

#12 김유 그래프, 문자열
  kimyoo04/.gitignore
  kimyoo04/그래프/BOJ 실버4 9372 상근이의 여행.py
  kimyoo04/그래프/그래프.md
  kimyoo04/문자열/BOJ 실버5 1316 그룹 단어 체커.py
Labels: 김유, python, easy

#15 김형준 스택
  brojoon1/stack/BOJ 실버2 1874 스택수열.py
Labels: python, easy, 김형준

#19 김유 트리
  kimyoo04/트리/BOJ 골드1 2042 구간 합 구하기.py
  kimyoo04/트리/BOJ 실버1 1991 트리 순회.py
  kimyoo04/트리/BOJ 실버2 11725 트리의 부모 찾기.py
Labels: 김유, python, easy, hard

#20 Jian1114
  jian1114/greedy/이지안 BOJ 실버1 1931 회의실 배정.py
  jian1114/greedy/이지안 BOJ 실버1 1946 신입사원.py
Labels: python, normal, 이지안

#22 Create code : 이지안 BOJ 골드4 14500 테트로미노
  jian1114/implementation/이지안 BOJ 골드4 14500 테트로미노.py
Labels: python, hard, 이지안

#17 Create code : 박진우 DFS
  ParkRang/DFS/BOJ 실버2 1012 유기농 배추.py
  ParkRang/DFS/BOJ 실버2 2210 숫자판 점프.py
  ParkRang/DFS/PGS level2 43165 타겟 넘버.py
Labels: python, easy, normal

#25 Create code : 김형준 BOJ 골드4 14500 테트로미노
  brojoon1/stack/BOJ 실버2 1874 스택수열.py
  brojoon1/구현/BOJ 골드4 14500 테르로미노.py
  brojoon1/해시/PGS level1 폰켓몬.py
  brojoon1/해시/PSG level2 전화번호 목록.py
  brojoon1/해시/해시.md
Labels: python, easy, 김형준

#26 위예진 힙, 스택, 큐
  bokkuembab/heap/BOJ 실버2 1928 최소힙.py
  bokkuembab/queue/BOJ 실버4 10845 큐.py
  bokkuembab/stack/BOJ 브론즈2 17608 막대기.py
  bokkuembab/stack/BOJ 실버5 1094 막대기.py
Labels: python, 위예진, normal

#27 Merge : 윤용완
  ayocado/BFS,DFS/PGS level2 1844 게임 맵 최단거리.py
  ayocado/BFS,DFS/PGS level2 43165 타겟넘버.py
  ayocado/브루트포스/BOJ 골드4 14500 테트로미노.py
Labels: python, normal, 윤용완
