Repository AIVLE-School-3-1/algorithm-study, pull requests merged in 2023-05, with the labels that each got.

#118 김유 그리디
  kimyoo04/그리디/PGS level2 42883 큰 수 만들기.py
  kimyoo04/그리디/PGS level2 42885 구명보트.py
  kimyoo04/그리디/PGS level3 42861 섬 연결하기.py
Labels: 김유, python, easy, normal

#120 Create code : 이지안 PGS level3 42861 섬 연결하기
  jian1114/greedy/이지안 PGS level3 42861 섬 연결하기.py
Labels: python, normal, 이지안

#121 Merge : 안승주 그리디, DFS
  beginner0107/DFS/빛의경로.java
  beginner0107/DFS/양궁대회.java
  beginner0107/그리디/섬연결.java
Labels: hard, java

#122 Merge : 윤용완 그리디
  ayocado/그리디/PGS level3 42861 섬 연결하기.py
Labels: python, normal, 윤용완

#124 Merge : 위예진 back tracking
  bokkuembab/Dijkstra/PGS level3 42861 섬 연결하기.py
  bokkuembab/back tracking/BOJ 실버3 15649 N과 M (1).py
Labels: python, 위예진, hard

#125 김유 dfs, bfs, 구현
  kimyoo04/구현/PGS level2 17683 [3차] 방금그곡.py
  kimyoo04/구현/힙 자료구조.md
  kimyoo04/그래프/BOJ 실버2 1012 유기농 배추.py
  kimyoo04/그래프/BOJ 실버2 1206 DFS와 BFS (인접행렬).py
Labels: 김유, python, normal

#126 Create code : 박진우 Knapsack
  ParkRang/Knapsack/BOJ 골드5 3067 Coins.py
  ParkRang/Knapsack/BOJ 실버2 1535 안녕.py
  ParkRang/Knapsack/PGS LV3 거스름돈.py
  ParkRang/PGS LV2 17683 방금그곡.py
Labels: normal, 박진우

#129 Merge : 박희원 구현
  heewon00/구현/PGS level2 17683 [3차] 방금그곡.py
  heewon00/구현/PGS level2 72411 메뉴 리뉴얼.py
  heewon00/구현/PGS level2 92335 k진수에서 소수 개수 구하기.py
Labels: normal

#130 Merge : 위예진 BFS, Dijkstra
  bokkuembab/BFS/BOJ 실버2 2644 촌수계산.py
  bokkuembab/Dijkstra/BOJ 골드4 1753 최단경로.py
  bokkuembab/simulation/PGS 12977 level1 소수만들기.py
Labels: python, 위예진, normal

#132 Create code : 박진우 DP2
  ParkRang/DP/BOJ 실버1 1932 정수 삼각형.py
  ParkRang/DP/BOJ 실버2 4097 수익.py
  ParkRang/DP/BOJ 실버5 1010 다리 놓기.py
Labels: normal, 박진우

#133 Merge : 박희원 DP
  heewon00/DP/BOJ 골드5 9251 LCS.py
  heewon00/DP/BOJ 실버2 14430 자원 캐기.py
  heewon00/DP/BOJ 실버4 2839 설탕 배달.py
Labels: easy

#134 PR : 김인재 Heap
  Pang-dachu/Heap/BOJ 실버1 11286 절댓값 힙.py
  Pang-dachu/Heap/BOJ 실버2 11279 최대 힙.py
  Pang-dachu/Heap/BOJ 실버2 1927 최소 힙.py
  Pang-dachu/Heap/BOJ 실버2 2075 N번째 큰 수.py
Labels: normal

#135 Merge : 안승주 해시, DFS, 그리디, DP
  beginner0107/DFS/불량사용자.java
  beginner0107/DP/자원캐기.java
  beginner0107/그리디/기지국.java
  beginner0107/해시/베스트앨범.java
  beginner0107/해시/베스트앨범.py
Labels: python, easy, 안승주, java

#136 Create code : 이지안 BOJ 실버2 14430 자원캐기
  jian1114/dp/이지안 BOJ 실버2 14430 자원캐기.py
Labels: python, normal, 이지안

#137 Merge : 김형준 자원캐기
  brojoon1/DP/BOJ 실버2 14430 자원캐기.py
Labels: python, easy, 김형준

#138 Merge : 윤용완 DP
  ayocado/DP/BOJ 실버2 14430 자원 캐기.py
Labels: python, normal, 윤용완

#139 김유 DP
  kimyoo04/DP/BOJ 실버2 14430 자원 캐기.py
  kimyoo04/DP/BOJ 실버3 1463 1로 만들기.py
  kimyoo04/DP/BOJ 실버3 9095 1, 2, 3 더하기.py
Labels: 김유, python, easy, normal

#140 Merge : 위예진 DP
  bokkuembab/back tracking/BOJ 실버1 1932 정수 삼각형.py
  bokkuembab/back tracking/BOJ 실버2 14430 자원캐기.py
  bokkuembab/back tracking/BOJ 실버3 1463 1로 만들기.py
Labels: python, 위예진, normal
